{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.service.name" . }}
  labels:
    app: {{ .Values.redis.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.targetPort }}
    protocol: TCP
{{- end }}