{{- if and .Values.networkPolicy.enabled .Values.backend.enabled .Values.redis.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  labels:
    app: {{ .Values.backend.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.redis.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.backend.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
{{- end }}