apiVersion: apps/v1
kind: Deployment
metadata:
  name: yet-another-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yet-another-generator
  template:
    metadata:
      labels:
        app: yet-another-generator
    spec:
      containers:
      - name: yet-another-generator
        volumeMounts:
        - name: shm
          mountPath: /dev/shm
        image: tabul4r4s4/dataops_hw14:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi